### ISSUE TITLE
cargo install command

### ISSUE THREAD

**Issue by stolzkc** [terrence2/promptly#1]
I believe it should be `cargo install --git https://github.com/terrence2/promptly` instead of `cargo install promptly` in the installation instruction :)

**Comment by jamesdabbs-procore** [comment]
I hit the same thing and added a note to the README in https://github.com/terrence2/promptly/pull/2. FWIW, if you're in the project directory, you can just run `cargo install`.

**Comment by terrence2** [comment]
Landed PR2, fixing the issue!
